name: Typst Compile and Release PDF

on:
  push:
    tags:
      - '*' # Trigger workflow on tag pushes

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build PDF and Create Release
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Typst
        uses: lvignoli/typst-action@main

      - name: Compile Typst document
        run: typst compile main.typ

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
