name: Typst Compile and Release PDF

on:
  push:
    tags:
      - '*' # Trigger workflow on tag pushes

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build PDF and Create Release
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - run: typst compile resume.typ
      - uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
